#!/bin/bash

# Run alg hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    if [ -z "$(grep "^LSB_VERSION=" $file)" ] ; then
        # add missing LSB_VERSION=
        echo "LSB_VERSION=2.0" >> $file
    fi

    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=alg|' \
        -e "s|^DISTRIB_CODENAME=.*|DISTRIB_CODENAME=rolling|" \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"ALG\"|' \
        -e "s|^DISTRIB_RELEASE=\"\(.*\)\"|DISTRIB_RELEASE=rolling|" \
        -e 's|^LSB_VERSION=.*$|LSB_VERSION=2.0|'
}

Os_release() {
    local file=/etc/os-release

    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"ALG\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"ALG\"|' \
        -e 's|^ID=.*$|ID=alg|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://arkalinuxgui.org/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://arkalinuxgui.org/docs\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://https://arkalinuxgui.org/discuss/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/arch-linux-gui"|' \
        -e 's|^LOGO=.*$|LOGO=alg|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
}

Issues() {
    sed -i 's|Arch Linux|ALG|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
